# VecMem, part of the ACTS project (R&D line)
#
# (c) 2021 CERN for the benefit of the ACTS project
#
# Mozilla Public License Version 2.0

# Name for this "action".
name: Build Tests

# Perform the build tests on every push. Since the project is just that small.
on: [ push ]

# All the different build/test jobs.
jobs:

  # Native build job on an Ubuntu system
  ubuntu-native:

    # The name/type of the system to run on.
    runs-on: ubuntu-latest

    # The different build modes to test.
    strategy:
      matrix:
        BUILD_TYPE: [ "Release", "Debug" ]

    # The build/test steps to execute.
    steps:
    # Use a standard checkout of the code.
    - uses: actions/checkout@v2
    # Set up the build directory.
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    # Run the CMake configuration.
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} $GITHUB_WORKSPACE
    # Perform the build.
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build .
    # Run the unit test(s).
    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest --output-on-failure
